POSTGRESQL_HOST="${POSTGRESQL_HOST:-localhost}"
POSTGRESQL_PORT="${POSTGRESQL_PORT:-5432}"
POSTGRESQL_DBNAME="${POSTGRESQL_DBNAME:-lgpdjus_dev}"
POSTGRESQL_USER="${POSTGRESQL_USER:-postgres}"
POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD:-trustme}"
SQITCH_DEPLOY="${SQITCH_DEPLOY:-docker}"
API_PORT="${API_PORT:-8080}"
API_WORKERS="${API_WORKERS:-1}"

export POSTGRESQL_HOST
export POSTGRESQL_PORT
export POSTGRESQL_DBNAME
export POSTGRESQL_USER
export POSTGRESQL_PASSWORD
export SQITCH_DEPLOY
export API_PORT
export API_WORKERS
